plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: dev/*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feat/*
    prerelease: '${name.replace(/^feat\//g, "feat-")}'
  - name: test/*
    prerelease: '${name.replace(/^test\//g, "test-")}'
  - name: bugfix/*
    prerelease: '${name.replace(/^bugfix\//g, "bugfix-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'
